const q=(zh,en,choices,answer,whyZh,whyEn)=>({prompt:[zh,en],choices,answer,why:[whyZh,whyEn]});
const lesson=(id,ref,title,lead,key,widget,quiz,extra=[])=>({id,ref,title,lead,key,widget,quiz,extra});
export const chapters={
 5:{slug:'ionic-bonds',title:['離子鍵','Ionic bonds'],intro:['移動電子、配對電荷，親手組成離子化合物。','Move electrons and balance charges to build ionic compounds.'],lessons:[
  lesson('shells','5.1–5.2',['電子層與八隅體規則','Shells and the octet rule'],['先重溫前 20 種元素的電子排佈，再比較 He、Ne、Ar 的外層。','Revisit the first 20 elements, then compare the outer shells of He, Ne and Ar.'],['<strong class="key-blue">最外層電子</strong>參與成鍵。常見穩定排佈有 <strong class="key-green">8 粒外層電子</strong>；第一層填滿只需 <strong class="key-red">2 粒</strong>。','<strong class="key-blue">Outer-shell electrons</strong> take part in bonding. A common stable arrangement has <strong class="key-green">8 outer electrons</strong>; a full first shell has <strong class="key-red">2</strong>.'],'shells',[
   q('氖的電子排佈是甚麼？','What is the electron arrangement of neon?',[['2, 8','2, 8'],['2, 6','2, 6'],['8, 2','8, 2']],0,'氖有 10 粒電子，第一層 2 粒，第二層 8 粒。','Neon has 10 electrons: 2 in the first shell and 8 in the second.'),
   q('氦的第一層有幾粒電子便填滿？','How many electrons fill the first shell of helium?',[['8','8'],['2','2'],['4','4']],1,'第一層最多容納 2 粒電子。','The first shell holds up to 2 electrons.'),
   q('化學成鍵主要涉及哪些電子？','Which electrons are mainly involved in chemical bonding?',[['所有內層電子','All inner electrons'],['原子核內的電子','Electrons in the nucleus'],['最外層電子','Outer-shell electrons']],2,'原子核不含電子；這些簡單成鍵模型重新分配外層電子。','The nucleus contains no electrons. These simple bonding models redistribute outer-shell electrons.'),
  ],[['八隅體規則是常用模型，並非所有物質都符合。原子不會因為「想要」填滿而成鍵；鍵涉及帶電粒子之間的引力。','The octet rule is a useful pattern, not a universal rule. Atoms do not “want” a full shell; bonding involves attractions between charged particles.']]),
  lesson('ions','5.3',['把原子變成離子','Turn atoms into ions'],['加減電子，觀察電荷、電子數和電子層如何改變。','Add or remove electrons and watch the charge, electron count and shells change.'],['<strong class="key-red">失去電子 → 正離子</strong>；<strong class="key-blue">得到電子 → 負離子</strong>。質子數保持不變。','<strong class="key-red">Lose electrons → positive ion.</strong> <strong class="key-blue">Gain electrons → negative ion.</strong> The proton number stays the same.'],'ions',[
   q('Mg 變成 Mg²⁺ 時發生甚麼？','What happens when Mg becomes Mg²⁺?',[['失去 2 粒電子','Loses 2 electrons'],['得到 2 粒電子','Gains 2 electrons'],['失去 2 粒質子','Loses 2 protons']],0,'12 個正電荷、10 個負電荷，淨電荷是 2+。','12 positive charges and 10 negative charges give a net charge of 2+.'),
   q('Cl⁻ 有 17 粒質子。它有多少電子？','Cl⁻ has 17 protons. How many electrons does it have?',[['16','16'],['17','17'],['18','18']],2,'多一粒電子，所以帶一個負電荷。','It has one extra electron, giving one negative charge.'),
   q('O 得到 2 粒電子後的離子是？','Which ion forms when O gains 2 electrons?',[['O²⁺','O²⁺'],['O²⁻','O²⁻'],['O₂','O₂']],1,'右上角的 2− 是電荷；O₂ 的下標 2 是原子數。','The superscript 2− is charge; the subscript 2 in O₂ counts atoms.'),
  ],[['第 I、II、III 族的簡單金屬離子常帶 +1、+2、+3；第 V、VI、VII 族的簡單負離子常帶 −3、−2、−1。氫可形成 H⁺ 或 H⁻，視乎化合物；H⁺ 沒有電子，不具有八隅體。','Simple metal ions from Groups I, II and III commonly have charges +1, +2 and +3. Simple anions from Groups V, VI and VII commonly have charges −3, −2 and −1. Hydrogen can form H⁺ or H⁻ in different compounds; H⁺ has no electrons and does not have an octet.']]),
  lesson('transfer','5.4',['電子轉移與離子鍵','Electron transfer and ionic bonds'],['逐粒轉移電子；留意一個鎂原子為何需要兩個氯原子。','Transfer one electron at a time. Notice why one magnesium atom needs two chlorine atoms.'],['電子轉移形成離子；<strong class="key-green">相反電荷離子之間的強靜電引力</strong>才是離子鍵。','Electron transfer forms ions. An ionic bond is the <strong class="key-green">strong electrostatic attraction between oppositely charged ions</strong>.'],'transfer',[
   q('MgCl₂ 中有甚麼離子？','Which ions make up MgCl₂?',[['Mg⁺、Cl²⁻','Mg⁺ and Cl²⁻'],['Mg²⁺、Cl⁻','Mg²⁺ and Cl⁻'],['Mg²⁻、Cl⁺','Mg²⁻ and Cl⁺']],1,'一個 Mg²⁺ 與兩個 Cl⁻ 的總電荷是零。','One Mg²⁺ and two Cl⁻ ions have zero total charge.'),
   q('離子鍵是甚麼？','What is an ionic bond?',[['電子在兩原子間共享','Electrons shared between atoms'],['兩個正離子相吸','Attraction between two positive ions'],['相反電荷離子間的引力','Attraction between oppositely charged ions']],2,'轉移電子是形成離子的過程；鍵是離子之間的引力。','Transfer is the process that forms ions; the bond is the attraction between them.'),
   q('固體 NaCl 由獨立 NaCl 分子組成嗎？','Does solid NaCl consist of separate NaCl molecules?',[['不是，是重複排列的離子晶格','No: it is a repeating ionic lattice'],['是，一對就是一個分子','Yes: each pair is a molecule'],['只有中性鈉原子','It contains only neutral sodium atoms']],0,'NaCl 表示 Na⁺ : Cl⁻ = 1 : 1，不是獨立分子。','NaCl gives the 1 : 1 ratio of Na⁺ to Cl⁻, not a separate molecule.'),
  ]),
  lesson('formula','5.4 / 5.6',['配平電荷，寫化學式','Balance charges, build formulae'],['增加正離子和負離子，令總電荷為零，再找最簡整數比。','Add cations and anions until the total charge is zero, then find the simplest whole-number ratio.'],['<strong class="key-blue">總正電荷 = 總負電荷</strong>。下標表示<strong class="key-green">最簡離子比例</strong>，不是離子電荷。','<strong class="key-blue">Total positive charge = total negative charge.</strong> Subscripts show the <strong class="key-green">simplest ion ratio</strong>, not ionic charges.'],'formula',[
   q('Al³⁺ 和 O²⁻ 的最簡比例是？','What is the simplest ratio of Al³⁺ to O²⁻?',[['3 : 2','3 : 2'],['2 : 3','2 : 3'],['1 : 1','1 : 1']],1,'2 × (+3) + 3 × (−2) = 0，所以是 Al₂O₃。','2 × (+3) + 3 × (−2) = 0, so the formula is Al₂O₃.'),
   q('Mg²⁺ 和 O²⁻ 的化學式是？','What is the formula from Mg²⁺ and O²⁻?',[['Mg₂O₂','Mg₂O₂'],['MgO₂','MgO₂'],['MgO','MgO']],2,'2 : 2 必須約簡為 1 : 1。','The ratio 2 : 2 must be reduced to 1 : 1.'),
   q('Ca²⁺ 和 NO₃⁻ 的化學式是？','What is the formula from Ca²⁺ and NO₃⁻?',[['Ca(NO₃)₂','Ca(NO₃)₂'],['CaNO₃₂','CaNO₃₂'],['Ca₂NO₃','Ca₂NO₃']],0,'需要兩個完整的硝酸根離子，所以使用括號。','Two whole nitrate ions are needed, so use brackets.'),
  ]),
  lesson('conductivity','5.5',['甚麼情況可以導電？','When can a substance conduct?'],['先預測燈泡會否亮起，再比較固態、熔融及水溶液中的粒子。','Predict whether the bulb lights, then compare particles in solids, melts and solutions.'],['NaCl 中的離子帶電，但固態時不能自由移動。熔融或溶於水後，<strong class="key-green">可移動的離子</strong>能傳導電流。','NaCl ions are charged but cannot move freely in the solid. In a melt or aqueous solution, <strong class="key-green">mobile ions</strong> carry current.'],'conductivity',[
   q('固體 NaCl 為何不導電？','Why does solid NaCl not conduct electricity?',[['沒有離子','It has no ions'],['離子不能自由移動','Its ions cannot move freely'],['離子沒有電荷','Its ions have no charge']],1,'帶電粒子還必須能移動，才能傳導電流。','Charged particles must also be mobile to carry current.'),
   q('熔融 NaCl 中傳導電流的是？','What carries current in molten NaCl?',[['自由移動的離子','Mobile ions'],['只有中性原子','Only neutral atoms'],['晶格內的質子','Protons in the lattice']],0,'Na⁺ 與 Cl⁻ 均能移動。','Both Na⁺ and Cl⁻ ions can move.'),
   q('哪種物質是電解質？','Which substance is an electrolyte?',[['銅','Copper'],['糖','Sugar'],['氯化鈉','Sodium chloride']],2,'NaCl 熔融或溶於水時導電，並可在電極發生化學變化。','NaCl conducts when molten or dissolved, with chemical changes at electrodes.'),
  ],[['導電體（例如銅）導電時本身通常不發生化學改變；電解質在熔融或水溶液中以離子導電，通電時電極可發生化學變化；非導電體在測試中不會明顯導電。','Conductors such as copper normally conduct without themselves changing chemically. Electrolytes conduct through ions when molten or in solution, with chemical changes possible at electrodes. Non-conductors do not appreciably conduct in the test.'],['金屬和石墨靠可移動電子導電。糖溶液沒有足夠可移動離子；蒸餾水只有極微弱導電性。並非所有共價物質的水溶液都不導電，例如 HCl 在水中形成離子。','Metals and graphite conduct through mobile electrons. Sugar solution lacks mobile ions; distilled water conducts only very weakly. Some covalent substances, such as HCl, form ions in water and their solutions conduct.']]),
  lesson('names','5.6',['離子名稱與化學式','Ion names and formulae'],['配對名稱、電荷和符號；比較銅(I)和銅(II)。','Match names, charges and symbols; compare copper(I) with copper(II).'],['羅馬數字表示金屬離子的<strong class="key-red">電荷數</strong>。多原子離子是一組原子，帶有<strong class="key-blue">整體電荷</strong>。','A Roman numeral gives the metal ion’s <strong class="key-red">charge</strong>. A polyatomic ion is a group of atoms with an <strong class="key-blue">overall charge</strong>.'],'names',[
   q('iron(III) ion 的符號是？','What is the symbol for iron(III) ion?',[['Fe³⁺','Fe³⁺'],['Fe₃','Fe₃'],['Fe³⁻','Fe³⁻']],0,'III 表示 3+ 電荷，並非三個鐵原子。','III means a 3+ charge, not three iron atoms.'),
   q('哪個是多原子離子？','Which is a polyatomic ion?',[['Na⁺','Na⁺'],['NH₄⁺','NH₄⁺'],['Cl⁻','Cl⁻']],1,'銨離子含 1 個氮和 4 個氫，整組帶 1+。','Ammonium has 1 nitrogen and 4 hydrogens; the whole group has charge 1+.'),
   q('Cu₂O 的英文名稱是？','What is the name of Cu₂O?',[['Copper(II) oxide','Copper(II) oxide'],['Copper oxide(II)','Copper oxide(II)'],['Copper(I) oxide','Copper(I) oxide']],2,'O²⁻ 需兩個 Cu⁺ 配平，所以銅離子是 +1。','O²⁻ needs two Cu⁺ ions for balance, so copper has charge +1.'),
  ],[['參考表採用 Hg₂²⁺ 表示汞(I)離子：兩個汞原子合起來帶 2+，每個汞為 +1。','The reference uses Hg₂²⁺ for mercury(I): two mercury atoms form an ion of overall charge 2+, with each mercury at +1.']]),
  lesson('colours','5.7',['從溶液顏色認識離子','Recognise ions by solution colour'],['先觀察試管顏色，再辨認可能存在的離子。','Observe the colour in the tube, then identify a possible ion.'],['顏色是<strong class="key-blue">線索</strong>，未必能單獨確認離子。濃度和溶液環境也會影響顏色。','Colour is a <strong class="key-blue">clue</strong>, not always a unique identification. Concentration and the solution environment also affect colour.'],'colours',[
   q('MnO₄⁻ 溶液的常見顏色是？','What colour is a typical MnO₄⁻ solution?',[['紫色','Purple'],['橙色','Orange'],['無色','Colourless']],0,'高錳酸根離子呈紫色。','Permanganate ions are purple.'),
   q('Fe²⁺ 的常見水溶液顏色是？','What is the usual colour of aqueous Fe²⁺?',[['深藍','Deep blue'],['淡綠','Pale green'],['紫','Purple']],1,'鐵(II)為淡綠；鐵(III)常呈黃至棕色。','Iron(II) is pale green; iron(III) is commonly yellow to brown.'),
   q('無色溶液是否代表沒有離子？','Does a colourless solution contain no ions?',[['一定沒有','Always'],['只有電子','It contains only electrons'],['不是，例如 NaCl 溶液含無色離子','No: NaCl solution contains colourless ions']],2,'無色和不帶電是不同概念。','Colourless and uncharged mean different things.'),
  ],[['只討論確實形成的水溶液。難溶固體（例如 ZnS）不應直接當成「ZnS 溶液」來預測顏色。','These examples refer to actual aqueous solutions. A sparingly soluble solid such as ZnS should not simply be treated as a “ZnS solution”.']]),
  lesson('lab','實驗 / Experiments',['離子遷移與焰色測試','Ion migration and flame tests'],['先預測離子的移動方向；再以焰色辨認四種金屬。','Predict ion movement, then use flame colours to distinguish four metals.'],['<strong class="key-blue">負離子 → 正極</strong>；<strong class="key-red">正離子 → 負極</strong>。焰色與溶液顏色是兩種不同觀察。','<strong class="key-blue">Anions → positive electrode.</strong> <strong class="key-red">Cations → negative electrode.</strong> Flame colour and solution colour are different observations.'],'lab',[
   q('紫色 MnO₄⁻ 會移向哪一極？','Which electrode attracts purple MnO₄⁻?',[['負極','Negative'],['正極','Positive'],['不移動','Neither']],1,'負離子受正極吸引；K⁺ 則移向負極。','The anion is attracted to the positive electrode; K⁺ moves towards the negative electrode.'),
   q('鈉化合物的典型焰色是？','What is the typical flame colour of sodium compounds?',[['紫','Purple'],['藍綠','Blue-green'],['黃','Yellow']],2,'鈉呈明亮黃色；鉀呈淡紫色。','Sodium gives a bright yellow flame; potassium gives lilac.'),
   q('焰色測試前清潔金屬線的目的是？','Why is the wire cleaned before a flame test?',[['避免殘留物影響焰色','To avoid contamination of the flame colour'],['增加樣本的電荷','To increase the sample charge'],['把離子變成分子','To turn ions into molecules']],0,'其他鹽的殘留可能遮蓋樣本的顏色。','Residues of other salts may mask the sample colour.'),
  ],[['這是虛擬觀察。真實焰色和離子遷移實驗由老師在實驗室帶領。金屬鹽也能產生煙花的顏色；這裏只探討顏色，不製作煙花。','These are virtual observations. Real flame and ion-migration experiments are teacher-led laboratory work. Metal salts also produce firework colours; this lesson explores colour, not firework preparation.']]),
 ]},
 6:{slug:'covalent-bonds',title:['共價鍵','Covalent bonds'],intro:['共享電子、畫分子，再由化學式算出相對質量。','Share electrons, draw molecules and calculate relative masses from formulae.'],lessons:[
  lesson('sharing','成鍵 / Bonding',['共享電子是甚麼？','What does sharing electrons mean?'],['從兩個氫原子開始，親手加入一對共享電子。','Start with two hydrogen atoms and add a shared pair of electrons.'],['共價鍵涉及<strong class="key-green">共享電子對</strong>與兩個帶正電原子核之間的<strong class="key-blue">強靜電引力</strong>。','A covalent bond involves <strong class="key-blue">strong electrostatic attraction</strong> between a <strong class="key-green">shared electron pair</strong> and both positive nuclei.'],'sharing',[
   q('一對共享電子共有幾粒電子？','How many electrons are in one shared pair?',[['1','1'],['2','2'],['4','4']],1,'一對就是兩粒；在本課例子中，每個原子提供一粒。','A pair has two electrons; in these examples each atom contributes one.'),
   q('H₂ 中每個 H 計算到多少粒外層電子？','How many outer-shell electrons does each H count in H₂?',[['2','2'],['1','1'],['8','8']],0,'共享的一對同時計入兩個氫原子的第一層。','The shared pair counts towards the first shell of both hydrogen atoms.'),
   q('點和叉代表甚麼？','What do dots and crosses represent?',[['不同電荷的電子','Electrons with different charges'],['質子與中子','Protons and neutrons'],['來自不同原子的電子','Electrons originating from different atoms']],2,'所有電子都相同並帶負電；符號只用來追蹤來源。','All electrons are identical and negative; the symbols only track origin.'),
  ],[['離子鍵：相反電荷離子相吸。共價鍵：原子核吸引共享電子。金屬鍵：金屬正離子與離域電子相吸。成鍵不會改變原子核內的質子數。','Ionic bonding attracts opposite ions; covalent bonding attracts nuclei to shared electrons; metallic bonding attracts metal cations to delocalised electrons. Bonding does not change proton numbers.']]),
  lesson('bonds','共享規則 / Sharing rules',['單鍵、雙鍵、三鍵','Single, double and triple bonds'],['試加 1、2、3 對電子，找出 Cl₂、O₂ 和 N₂ 的正確圖。','Try 1, 2 or 3 shared pairs and complete the diagrams for Cl₂, O₂ and N₂.'],['<strong class="key-green">1 對 → 單鍵；2 對 → 雙鍵；3 對 → 三鍵。</strong>共享電子要計入兩端原子的外層。','<strong class="key-green">1 pair → single; 2 pairs → double; 3 pairs → triple bond.</strong> Count shared electrons for both bonded atoms.'],'bonds',[
   q('O₂ 有多少對共享電子？','How many shared pairs are in O₂?',[['1','1'],['3','3'],['2','2']],2,'每個氧有 6 粒外層電子，共享兩對便各計到 8 粒。','Each O has 6 outer electrons; two shared pairs let each count 8.'),
   q('N≡N 的三條線代表？','What do the three lines in N≡N represent?',[['3 對共享電子','3 shared pairs'],['3 粒電子','3 electrons'],['3 個氮原子','3 nitrogen atoms']],0,'三鍵共有 6 粒成鍵電子。','A triple bond contains 6 bonding electrons.'),
   q('Cl₂ 每個 Cl 有幾對孤電子？','How many lone pairs does each Cl have in Cl₂?',[['1','1'],['3','3'],['4','4']],1,'每個 Cl 有 3 對孤電子，加 1 對共享電子，共計 8 粒。','Each Cl has 3 lone pairs and counts 1 shared pair, giving 8 electrons.'),
  ]),
  lesson('molecules','分子 / Molecules',['元素分子與獨立原子','Element molecules and separate atoms'],['比較 He、H₂、O₂、N₂、Cl₂ 和 O₃：數原子，再分辨種類。','Compare He, H₂, O₂, N₂, Cl₂ and O₃: count atoms and distinguish particle types.'],['元素只含<strong class="key-blue">一種原子</strong>，不代表每個粒子只能有一個原子。貴氣體通常以<strong class="key-green">獨立原子</strong>存在。','An element contains <strong class="key-blue">one type of atom</strong>, not necessarily one atom per particle. Noble gases normally exist as <strong class="key-green">separate atoms</strong>.'],'molecules',[
   q('O₃ 是元素還是化合物？','Is O₃ an element or a compound?',[['化合物，有三個原子','Compound: it has three atoms'],['元素，只含氧原子','Element: it contains only oxygen atoms'],['混合物','Mixture']],1,'原子種類而非數量決定是否為元素。','The types of atoms, not their number, determine whether it is an element.'),
   q('氦在一般情況下的粒子是？','What particles normally make up helium?',[['He₂','He₂'],['He₃','He₃'],['獨立的 He 原子','Separate He atoms']],2,'氦是單原子氣體。','Helium is a monatomic gas.'),
   q('哪個是雙原子分子？','Which is a diatomic molecule?',[['N₂','N₂'],['Ne','Ne'],['O₃','O₃']],0,'N₂ 由兩個氮原子組成。','N₂ contains two nitrogen atoms.'),
  ]),
  lesson('compounds','共價化合物 / Compounds',['親手畫共價化合物','Build covalent compound diagrams'],['加入成鍵電子對和孤電子對，完成 HCl、H₂O、NH₃、CH₄、CO₂ 等圖。','Add bonding and lone pairs to complete HCl, H₂O, NH₃, CH₄, CO₂ and more.'],['<strong class="key-blue">成鍵電子對</strong>在兩原子之間；<strong class="key-red">孤電子對</strong>沒有參與成鍵。分清「對數」和「電子粒數」。','<strong class="key-blue">Bonding pairs</strong> lie between atoms; <strong class="key-red">lone pairs</strong> are not shared in a bond. Distinguish pairs from the number of electrons.'],'compounds',[
   q('H₂O 的氧原子有幾對孤電子？','How many lone pairs are on oxygen in H₂O?',[['0','0'],['2','2'],['4','4']],1,'氧有 2 對孤電子和 2 對成鍵電子。','Oxygen has 2 lone pairs and 2 bonding pairs.'),
   q('CH₄ 一共有多少粒成鍵電子？','How many bonding electrons are there in CH₄?',[['4','4'],['2','2'],['8','8']],2,'4 條單鍵 × 每鍵 2 粒電子 = 8 粒。','4 single bonds × 2 electrons per bond = 8 electrons.'),
   q('CO₂ 的結構式是？','Which is the structural formula of CO₂?',[['O=C=O','O=C=O'],['O−C−O','O−C−O'],['C−O−O','C−O−O']],0,'兩條 C=O 雙鍵令三個原子各符合八隅體。','Two C=O double bonds give all three atoms octets.'),
  ]),
  lesson('formulae','化學式 / Formulae',['分子式與結構式','Molecular and structural formulae'],['一個表示原子數目；另一個表示原子怎樣相連。','One counts atoms; the other shows how they connect.'],['分子式顯示一個分子的<strong class="key-blue">原子種類和數目</strong>；結構式顯示<strong class="key-green">原子之間的鍵</strong>。','A molecular formula shows <strong class="key-blue">atom types and numbers</strong> in one molecule; a structural formula shows <strong class="key-green">bonds between atoms</strong>.'],'formulae',[
   q('CH₄ 的下標 4 表示？','What does the 4 in CH₄ mean?',[['碳帶 4+','Carbon has charge 4+'],['每個分子有 4 個氫原子','4 H atoms per molecule'],['共有 4 個分子','4 molecules']],1,'沒有下標的 C 表示一個碳原子。','C without a subscript means one carbon atom.'),
   q('在本課的簡單模型中，碳通常形成幾條共價鍵？','In this lesson’s simple model, how many bonds does carbon usually form?',[['2','2'],['3','3'],['4','4']],2,'例如 CH₄ 有 4 條單鍵；CO₂ 有 2 條雙鍵。','CH₄ has 4 single bonds; CO₂ has 2 double bonds.'),
   q('結構式比單用分子式多顯示甚麼？','What extra information does a structural formula show?',[['原子如何相連','How atoms connect'],['樣本溫度','Sample temperature'],['溶液顏色','Solution colour']],0,'線表示原子間的鍵；並非所有平面圖都表示真實三維形狀。','Lines represent bonds. A flat diagram need not show the actual 3D shape.'),
  ],[['這些練習指定本課的常見成鍵數：H 和鹵素 1、O 和 S 2、N 和 P 3、C 和 Si 4。只知道兩種元素，並不一定能唯一決定所有可能化合物。','These tasks specify the common bond counts used here: H and halogens 1; O and S 2; N and P 3; C and Si 4. Two element names alone do not uniquely identify every possible compound.']]),
  lesson('mass','相對質量 / Relative mass',['數清原子，再計相對質量','Count atoms, then calculate mass'],['先拆開括號與下標，再把各原子的相對原子質量相加。','Expand brackets and subscripts, then add the relative atomic masses.'],['相對分子質量 / 相對式量 = <strong class="key-green">Σ（原子數 × 相對原子質量）</strong>。它們是相對值，<strong class="key-blue">沒有單位</strong>。','Relative molecular / formula mass = <strong class="key-green">Σ (atom count × relative atomic mass)</strong>. These relative values have <strong class="key-blue">no unit</strong>.'],'mass',[
   q('H₂O 的相對分子質量是？（H=1，O=16）','What is the relative molecular mass of H₂O? (H=1, O=16)',[['17','17'],['18','18'],['34','34']],1,'2 × 1 + 16 = 18。','2 × 1 + 16 = 18.'),
   q('Ca(NO₃)₂ 有多少個氧原子？','How many oxygen atoms are in Ca(NO₃)₂?',[['3','3'],['2','2'],['6','6']],2,'括號外的 2 乘以括號內的 3。','The 2 outside the bracket multiplies the 3 inside.'),
   q('NaCl 應用哪個名稱計算相對質量？','Which term is appropriate for the relative mass of NaCl?',[['相對式量','Relative formula mass'],['相對分子質量','Relative molecular mass'],['電子質量','Electron mass']],0,'離子晶格沒有獨立 NaCl 分子，以式量計算一個化學式比例。','An ionic lattice has no separate NaCl molecules; use relative formula mass.'),
  ]),
 ]},
};
