import {chapters} from './content.js';
import {mountWidget} from './widgets.js';
import {molecules} from './chemistry.js';
import {moleculeSVG,latticeSVG} from './diagrams.js';

const unit=Number(document.body.dataset.unit),chapter=chapters[unit];
const safeRead=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}};
const save=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));}catch{/* Lesson remains usable without storage. */}};
const requested=new URL(location.href).searchParams.get('lang');
let language=['en','zh'].includes(requested)?requested:safeRead('chem-bonding-language','zh');
const active=chapter.lessons.find(l=>l.id===location.pathname.match(/\/sessions\/([a-z]+)\/?$/)?.[1]);
const quizAnswers=new Map();
const t=(zh,en)=>language==='en'?en:zh,bi=pair=>pair[language==='en'?1:0];
const lessonUrl=id=>`./sessions/${id}/?lang=${language}`;
const refLabel=ref=>ref.includes(' / ')?ref.split(' / ')[language==='en'?1:0]:ref;
const homeUrl=()=>`./?lang=${language}`;
const widgetTitles={shells:['建立電子排佈圖','Build an electron diagram'],ions:['自己形成離子','Make an ion'],transfer:['一步一步轉移電子','Transfer electrons, step by step'],formula:['電荷配平工作台','Charge balance workbench'],conductivity:['預測，然後測試','Predict, then test'],names:['離子名稱配對','Match ion names'],colours:['觀察顏色，辨認離子','Observe and identify'],lab:['虛擬焰色與離子遷移','Virtual flames and ion migration'],sharing:['建立第一條共價鍵','Build your first covalent bond'],bonds:['試出正確的共享對數','Find the right number of shared pairs'],molecules:['數一數粒子中的原子','Count atoms in each particle'],compounds:['親手建立電子圖','Build an electron diagram'],formulae:['由成鍵數建立分子式','Build a molecular formula'],mass:['分步計算相對質量','Calculate relative mass step by step']};

function renderHome(){return `<div class="breadcrumb"><span>${t('中三化學','Form 3 Chemistry')}</span><span>/</span><b>UNIT 0${unit}</b></div><section class="bonding-hero panel"><div><span class="eyebrow">UNIT 0${unit} · ${t('互動教材','INTERACTIVE CHEMISTRY')}</span><h1>${bi(chapter.title)}</h1><p>${bi(chapter.intro)}</p><a class="primary-link" href="${lessonUrl(chapter.lessons[0].id)}">${t('開始學習','Start learning')} →</a><div class="hero-badges"><span>${chapter.lessons.length} ${t('個課題','lessons')}</span><span>${chapter.lessons.length*3} ${t('條小測','checkpoint questions')}</span><span>${t('練習 · 提示 · 示範','Practice · hints · examples')}</span></div></div><div class="hero-model">${unit===5?latticeSVG():moleculeSVG(molecules.find(m=>m.id==='H2O'))}<b>${unit===5?t('轉移電子 · 相反電荷相吸','Transfer electrons · opposite charges attract'):t('共享電子 · 一起計入外層','Share electrons · count them for both atoms')}</b></div></section><div class="catalog-heading"><div><span class="eyebrow">CHOOSE A LESSON</span><h2>${t('選一課開始','Choose a lesson')}</h2></div></div><nav class="catalog-grid" aria-label="${t('課題目錄','Lesson directory')}">${chapter.lessons.map((l,i)=>`<a class="catalog-card" href="${lessonUrl(l.id)}"><span class="catalog-number">${String(i+1).padStart(2,'0')}</span><span><small>${refLabel(l.ref)}</small><b>${bi(l.title)}</b><p>${bi(l.lead)}</p></span><span class="catalog-arrow" aria-hidden="true">↗</span></a>`).join('')}</nav><div class="study-guide panel"><h2>${t('每課怎樣學？','How to use each lesson')}</h2><ol><li>${t('看重點句，先作預測。','Read the key idea and make a prediction.')}</li><li>${t('親手操作，再按「檢查答案」。','Build it yourself, then check your answer.')}</li><li>${t('讀錯誤提示，再試一次；需要時才看示範。','Read the feedback and retry; use the example when needed.')}</li><li>${t('切換另一例子，最後完成小測。','Try another example, then complete the checkpoint.')}</li></ol></div>`;}
function renderQuiz(){return `<section class="checkpoint panel" aria-label="${t('小測一下','Quick check')}"><div class="checkpoint-head"><div><span class="eyebrow">CHECKPOINT</span><h2>${t('小測一下','Quick check')}</h2></div><span id="quiz-score"></span></div>${active.quiz.map((q,i)=>`<article class="quiz-item"><h3><span>${String(i+1).padStart(2,'0')}</span>${bi(q.prompt)}</h3><div class="quiz-choices" role="group" aria-label="${bi(q.prompt)}">${q.choices.map((c,j)=>`<button type="button" data-question="${i}" data-choice="${j}" aria-pressed="false"><span>${'ABC'[j]}</span>${bi(c)}</button>`).join('')}</div><p class="quiz-feedback" data-feedback="${i}" role="status"></p></article>`).join('')}<button type="button" class="secondary-button" id="retry-quiz">${t('重新練習這三題','Retry these three questions')}</button></section>`;}
function renderLesson(){const i=chapter.lessons.indexOf(active);return `<div class="breadcrumb"><a href="${homeUrl()}">${t('課題目錄','All lessons')}</a><span>/</span><b>${bi(active.title)}</b><span class="breadcrumb-count">${String(i+1).padStart(2,'0')} / ${String(chapter.lessons.length).padStart(2,'0')}</span></div><div class="lesson-heading"><span class="eyebrow">UNIT 0${unit} · ${refLabel(active.ref)}</span><h1>${bi(active.title)}</h1><p>${bi(active.lead)}</p></div><aside class="key-idea">${bi(active.key)}</aside><section class="learning-lab panel" aria-labelledby="practice-heading"><div class="lab-heading"><div><span class="eyebrow">YOUR TURN</span><h2 id="practice-heading">${bi(widgetTitles[active.widget])}</h2></div><span>INTERACTIVE</span></div><div id="widget"></div></section>${active.extra.map(p=>`<p class="lesson-note">${bi(p)}</p>`).join('')}${renderQuiz()}<nav class="lesson-pager" aria-label="${t('課題導覽','Lesson navigation')}"><a href="${i?lessonUrl(chapter.lessons[i-1].id):homeUrl()}">← ${i?t('上一課','Previous'):t('課題目錄','All lessons')}</a><a href="${i<chapter.lessons.length-1?lessonUrl(chapter.lessons[i+1].id):`../${unit===5?'covalent-bonds':'ionic-bonds'}/?lang=${language}`}">${i<chapter.lessons.length-1?t('下一課','Next lesson'):t(unit===5?'前往 Unit 6':'重溫 Unit 5',unit===5?'Continue to Unit 6':'Revisit Unit 5')} →</a></nav>`;}
function updateQuiz(){let correct=0;active.quiz.forEach((q,i)=>{const choice=quizAnswers.get(i),selected=choice!==undefined,good=choice===q.answer;if(good)correct++;document.querySelectorAll(`[data-question="${i}"]`).forEach(b=>{b.setAttribute('aria-pressed',String(+b.dataset.choice===choice));b.classList.toggle('correct',selected&&good&&+b.dataset.choice===choice);});const feedback=document.querySelector(`[data-feedback="${i}"]`);feedback.textContent=selected?(good?t('答對了！ ','Correct. '):t('再試一次。 ','Try again. '))+bi(q.why):'';feedback.classList.toggle('is-correct',good);});document.querySelector('#quiz-score').textContent=`${correct} / 3 ${t('答對','correct')}`;}
function render(){
 document.documentElement.lang=language==='en'?'en':'zh-Hant-HK';document.title=(active?bi(active.title)+' · ':'')+bi(chapter.title)+' · CHEM Explore';save('chem-bonding-language',language);
 document.querySelector('#brand-link').href=homeUrl();document.querySelector('#course-label').textContent=`S3 · ${bi(chapter.title).toUpperCase()}`;
 document.querySelector('#skip-link').textContent=t('跳到課堂內容','Skip to lesson');document.querySelector('#skip-link').href=location.pathname+location.search+'#main';
 document.querySelector('#side-heading').innerHTML=`<span>UNIT 0${unit}</span><b>${bi(chapter.title)}</b><small>${String(chapter.lessons.length).padStart(2,'0')}</small>`;
 document.querySelector('#lesson-nav').innerHTML=`<a class="classroom-home-link" href="${homeUrl()}" ${!active?'aria-current="page"':''}><svg aria-hidden="true"><use href="../classroom-icons.svg#home"/></svg><b>${t('課題目錄','All lessons')}</b></a>`+chapter.lessons.map((l,i)=>`<a href="${lessonUrl(l.id)}" ${active===l?'aria-current="page"':''}><span>${String(i+1).padStart(2,'0')}</span><b>${bi(l.title)}</b></a>`).join('');
 const viewed=new Set(safeRead(`chem-unit-${unit}-viewed`,[]));if(active)viewed.add(active.id);save(`chem-unit-${unit}-viewed`,[...viewed]);
 document.querySelector('#progress-label').textContent=t('已瀏覽','Topics viewed');document.querySelector('#progress-count').textContent=`${viewed.size} / ${chapter.lessons.length}`;document.querySelector('#progress-fill').style.width=`${viewed.size/chapter.lessons.length*100}%`;
 document.querySelector('#all-units').textContent=t('← 返回單元總覽','← All units');document.querySelector('#all-units').href=`../?lang=${language}`;
 document.querySelector('#main').innerHTML=(active?renderLesson():renderHome())+`<footer class="site-footer"><p>${t(`根據 Unit ${unit} 學生筆記整理；圖像為簡化教學模型。`,`Based on the Unit ${unit} student notes; diagrams are simplified teaching models.`)}</p><details><summary>${t('教材參考','Teaching references')}</summary><a href="https://edu.rsc.org/structure-and-bonding/chemical-misconceptions-i-chemical-bonding/1140.article">RSC · Chemical bonding</a><a href="https://www.open.edu/openlearn/mod/oucontent/view.php?id=87848&amp;section=_unit4.2.3">Open University · Ionic structures</a><a href="https://edu.rsc.org/experiments/flame-tests-the-wooden-splint-method/759.article">RSC · Flame tests</a></details></footer>`;
 if(active){mountWidget(document.querySelector('#widget'),active.widget,language);updateQuiz();}
 document.querySelectorAll('[data-language]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.language===language)));
 document.querySelector('#menu-button').setAttribute('aria-label',t('開啟課題目錄','Open lesson menu'));document.querySelector('#nav-backdrop').setAttribute('aria-label',t('關閉課題目錄','Close lesson menu'));
}
const menu=document.querySelector('#menu-button'),backdrop=document.querySelector('#nav-backdrop');
function closeMenu(){document.body.classList.remove('menu-open');menu.setAttribute('aria-expanded','false');backdrop.hidden=true;}
menu.addEventListener('click',()=>{const open=!document.body.classList.contains('menu-open');document.body.classList.toggle('menu-open',open);menu.setAttribute('aria-expanded',String(open));backdrop.hidden=!open;});backdrop.addEventListener('click',closeMenu);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});
document.querySelectorAll('[data-language]').forEach(b=>b.addEventListener('click',()=>{language=b.dataset.language;const url=new URL(location.href);url.searchParams.set('lang',language);history.replaceState(null,'',url);closeMenu();render();}));
document.querySelector('#main').addEventListener('click',event=>{const b=event.target.closest('[data-question]');if(b){quizAnswers.set(+b.dataset.question,+b.dataset.choice);updateQuiz();}if(event.target.closest('#retry-quiz')){quizAnswers.clear();updateQuiz();}});
render();
