import {elements,shells,simpleIons,ions,ionHTML,formulaHTML,chargeText,ionicPairs,ratio,ionicFormula,molecules,pairTotal,loneTotal,valence,parseFormula,relativeMass,massOf,massExamples,molecularTasks} from './chemistry.js';
import {shellSVG,ionDiagram,moleculeSVG,latticeSVG} from './diagrams.js';

const states=new Map();
const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function mountWidget(root,type,language){
 const t=(zh,en)=>language==='en'?en:zh,bi=pair=>pair[language==='en'?1:0];
 const s=states.get(type)||{index:0,values:[],feedback:'',good:false,done:new Set()};states.set(type,s);
 if(s.language&&s.language!==language){s.feedback='';s.migrationFeedback='';}s.language=language;
 const button=(label,action,extra='',cls='')=>`<button type="button" class="${cls}" data-action="${action}" ${extra}>${label}</button>`;
 const options=(list,index)=>list.map((label,i)=>`<option value="${i}" ${i===index?'selected':''}>${label}</option>`).join('');
 const select=(label,list,key='index')=>`<label class="select-label">${label}<select data-select="${key}">${options(list,s[key]||0)}</select></label>`;
 const counter=(label,value,key,max=8)=>`<div class="count-row"><span>${label}</span><div>${button('−','count',`data-key="${key}" data-delta="-1" aria-label="${t('減少','Remove')} ${safe(label)}" ${value<=0?'disabled':''}`)}<output>${value}</output>${button('+','count',`data-key="${key}" data-delta="1" data-max="${max}" aria-label="${t('增加','Add')} ${safe(label)}" ${value>=max?'disabled':''}`)}</div></div>`;
 const actions=()=>`<div class="practice-actions">${button(t('檢查答案','Check answer'),'check','','primary')}${button(t('提示','Hint'),'hint')}${button(t('看示範','Show example'),'example')}${button(t('下一個例子 →','Next example →'),'next')}</div>`;
 const feedback=()=>`<p class="lab-feedback ${s.good?'is-correct':s.mode==='error'?'is-error':''}" role="status" aria-live="polite">${s.feedback}</p>${type==='transfer'?'':`<p class="practice-progress">${t('未看示範已完成','Completed without the example')}: <b>${s.done.size}</b> ${t('個例子',s.done.size===1?'example':'examples')}</p>`}`;
 const split=(controls,visual)=>`<div class="practice-grid"><div class="practice-controls">${controls}</div><div class="practice-visual">${visual}</div></div>`;
 const legend=()=>`<p class="diagram-note"><b class="dot-key">●</b> / <b class="cross-key">×</b> ${t('代表不同原子原有的電子；所有電子相同。圖不按比例。','track the original atoms; all electrons are identical. Not to scale.')}</p>`;
 const numberInput=(label,key)=>`<label class="numeric-label">${label}<input type="number" min="0" step="any" data-input="${key}" value="${safe(s[key]??'')}" inputmode="decimal"/></label>`;
 const tell=(zh,en,good=false)=>{s.feedback=t(zh,en);s.good=good;if(good&&!s.revealed)s.done.add(s.index);};
 const reset=()=>{s.values=[];s.feedback='';s.good=false;s.revealed=false;s.answer='';s.moved=0;s.prediction=null;s.tested=false;s.lit=false;s.counts={};s.total='';};
 let count=1,renderContent,onAction;

 if(type==='shells'){
  count=elements.length;
  renderContent=()=>{const e=elements[s.index],target=shells(e.z);if(!s.values.length)s.values=target.map(()=>0);
   return split(select(t('選擇元素','Choose an element'),elements.map(e=>`${e.symbol} · ${bi(e.name)}`))+`<p>${t('原子序','Atomic number')} <b>${e.z}</b> · ${t('放入正確數目的電子，由內層開始。','Place the correct number of electrons, starting from the inside.')}</p>`+s.values.map((v,i)=>counter(`${t('第','Shell ')}${i+1}${t(' 層','')}`,v,i,[2,8,8,2][i])).join('')+actions(),shellSVG(e.symbol,s.values)+`<p>${t('先在四個位置各放一粒，再配對；第一層最多兩粒。','Place one at each of four positions, then pair; the first shell holds two.')}</p>`);
  };
  onAction=action=>{const e=elements[s.index],target=shells(e.z);if(action==='example'){s.values=target; s.revealed=true;tell(`示範：${e.symbol} 的排佈是 ${target.join(', ')}。`,`Example: ${e.symbol} has arrangement ${target.join(', ')}.`);}if(action==='hint')tell('先填內層：前 20 種元素依次用 2、8、8、2。','Fill the inside first: use 2, 8, 8, 2 for these first 20 elements.');if(action==='check'){const wrong=s.values.findIndex((v,i)=>v!==target[i]);if(wrong===-1)tell('正確！總電子數和各層排佈都正確。','Correct: both the total and the shell arrangement match.',true);else tell(`再試第 ${wrong+1} 層；總共應有 ${e.z} 粒電子。`,`Revisit shell ${wrong+1}; there should be ${e.z} electrons in total.`);}};
 }
 if(type==='ions'){
  count=simpleIons.length;
  renderContent=()=>{const e=simpleIons[s.index];if(!s.values.length)s.values=[e.z];const n=s.values[0],q=e.z-n;
   return split(select(t('選擇目標離子','Choose a target ion'),simpleIons.map(e=>`${e.symbol}${chargeText(e.charge)} · ${bi(e.name)}`))+`<p>${t('目標','Target')}: <b class="formula">${ionHTML(e)}</b></p>`+counter(t('電子數','Electrons'),n,0,20)+`<div class="count-facts"><span>${t('質子','Protons')} <b>${e.z}</b></span><span>${t('淨電荷','Net charge')} <b>${chargeText(q)}</b></span></div>`+actions(),shellSVG(e.symbol,shells(n),q)+`<p>${t('電荷 = 質子數 − 電子數','Charge = protons − electrons')}</p>`);
  };
  onAction=action=>{const e=simpleIons[s.index],n=e.z-e.charge;if(action==='hint')tell('負電荷表示電子比質子多；正電荷表示電子比質子少。','Negative charge means more electrons than protons; positive charge means fewer.');if(action==='example'){s.values=[n];s.revealed=true;tell(`${e.symbol}：${e.z} 粒質子，${n} 粒電子，電荷 ${chargeText(e.charge)}。`,`${e.symbol}: ${e.z} protons, ${n} electrons, charge ${chargeText(e.charge)}.`);}if(action==='check'){if(s.values[0]===n)tell(`正確！${e.charge>0?'移走':'加入'} ${Math.abs(e.charge)} 粒電子，質子數仍是 ${e.z}。`,`Correct: ${e.charge>0?'remove':'add'} ${Math.abs(e.charge)} electrons; proton number is still ${e.z}.`,true);else tell(`現在的電荷是 ${chargeText(e.z-s.values[0])}；目標是 ${chargeText(e.charge)}。`,`Your charge is ${chargeText(e.z-s.values[0])}; the target is ${chargeText(e.charge)}.`);}};
 }
 if(type==='transfer'){
  const pairs=ionicPairs.filter(p=>['NaCl','MgCl2','MgO','Na2O','CaF2','Al2O3','K3N'].includes(ionicFormula(...p)));count=pairs.length;
  renderContent=()=>{const [a,b]=pairs[s.index],[na,nb]=ratio(a,b),total=na*a.charge,moved=s.moved||0,finished=moved===total;
   const products=[];
   for(let i=0;i<na;i++){const lost=Math.min(a.charge,Math.max(0,moved-i*a.charge));products.push(ionDiagram(a.symbol,a.charge-lost,0,lost));}
   for(let i=0;i<nb;i++){const gained=Math.min(-Number(b.charge),Math.max(0,moved-i*(-Number(b.charge))));products.push(ionDiagram(b.symbol,8+b.charge,gained,-gained));}
   return select(t('選擇成鍵例子','Choose a bonding example'),pairs.map(p=>ionicFormula(...p)))+`<div class="transfer-story"><div><b>${na} ${a.symbol}</b><span>${t('提供電子','donate electrons')}</span></div><span class="transfer-arrow">${moved} / ${total} e⁻ →</span><div><b>${nb} ${b.symbol}</b><span>${t('接受電子','receive electrons')}</span></div></div><div class="ion-products">${products.join('')}</div><p class="diagram-note">${t('顯示參與轉移的外層電子。金屬失去原有外層電子後，新外層已填滿；此簡圖省略內層。','Shows valence electrons involved in transfer. The metal’s newly exposed shell is full after losing its original outer electrons; inner shells are omitted here.')}</p><div class="practice-actions">${button(t('轉移 1 粒電子','Transfer 1 electron'),'transfer',finished?'disabled':'','primary')}${button(t('重設','Reset'),'reset')}${button(t('下一個例子 →','Next example →'),'next')}</div><div class="transfer-result ${finished?'complete':''}">${finished?`<b class="formula">${formulaHTML(ionicFormula(a,b))}</b> · ${t('電子已轉移。離子仍藉相反電荷間的引力結合。','Transfer complete. Opposite ions attract one another.')}`:t('現在是逐步轉移的示意過程；完成後再觀察離子的電荷。','This is a step-by-step bookkeeping model; observe the final ion charges when transfer is complete.')}</div><details class="reference"><summary>${t('再放大看：離子晶格','Look further: the ionic lattice')}</summary>${latticeSVG()}<p>${t('以 NaCl 為例：離子向多個方向重複排列，每個離子吸引周圍的異號離子，不是獨立的 NaCl 分子。','NaCl example: ions repeat in many directions. Each attracts surrounding opposite ions; there are no separate NaCl molecules.')}</p></details>`;
  };
  onAction=action=>{if(action==='transfer'){const [a,b]=pairs[s.index],n=ratio(a,b)[0]*a.charge;s.moved=Math.min(n,(s.moved||0)+1);if(s.moved===n)tell('觀察完成！請到下方小測檢查理解。','Observation complete. Try the checkpoint below.',true);}if(action==='reset')reset();};
 }
 if(type==='formula'){
  count=ionicPairs.length;
  renderContent=()=>{const [a,b]=ionicPairs[s.index];if(!s.values.length)s.values=[1,1];const total=s.values[0]*a.charge+s.values[1]*b.charge;
   return split(select(t('選擇離子組合','Choose an ion pair'),ionicPairs.map(([a,b])=>`${a.symbol}${chargeText(a.charge)} + ${b.symbol}${chargeText(b.charge)}`))+counter(bi(a.name),s.values[0],0,6)+counter(bi(b.name),s.values[1],1,6)+actions(),`<div class="charge-tray"><div>${Array.from({length:s.values[0]},()=>`<span class="ion-chip positive">${ionHTML(a)}</span>`).join('')}</div><div>${Array.from({length:s.values[1]},()=>`<span class="ion-chip negative">${ionHTML(b)}</span>`).join('')}</div></div><div class="charge-total ${total===0?'balanced':''}">${t('總電荷','Total charge')}: <b>${total>0?'+':''}${total}</b></div><p>${s.values[0]} × (+${a.charge}) + ${s.values[1]} × (${b.charge}) = ${total}</p><p>${t('先令總電荷為零，再檢查是否最簡比。','Balance the charges, then check that the ratio is simplest.')}</p>`);
  };
  onAction=action=>{const [a,b]=ionicPairs[s.index],target=ratio(a,b),total=s.values[0]*a.charge+s.values[1]*b.charge;if(action==='hint')tell(`找 ${a.charge} 和 ${-Number(b.charge)} 的最小公倍數；正離子先寫。`,`Find the lowest common multiple of ${a.charge} and ${-Number(b.charge)}; write the cation first.`);if(action==='example'){s.values=target;s.revealed=true;tell(`示範比例 ${target.join(' : ')} → ${ionicFormula(a,b)}。`,`Example ratio ${target.join(' : ')} → ${ionicFormula(a,b)}.`);}if(action==='check'){if(s.values.some(n=>n===0))tell('化合物必須包含兩種離子。','Include both types of ion.');else if(total!==0)tell(`電荷尚未配平：現在合計 ${total>0?'+':''}${total}。`,`Charges are not balanced yet: your total is ${total>0?'+':''}${total}.`);else if(s.values.some((n,i)=>n!==target[i]))tell('電荷已配平！但比例仍可約簡，再試一次。','Charges balance, but the ratio can still be simplified. Try again.');else tell(`正確！${target.join(' : ')}，化學式 ${ionicFormula(a,b)}。`,`Correct: ${target.join(' : ')}, formula ${ionicFormula(a,b)}.`,true);}};
 }
 if(type==='conductivity'){
  const samples=[
   [['固體 NaCl','Solid NaCl'],false,'ions',['離子固定在晶格中，不能自由移動。','Ions are held in the lattice and cannot move freely.']],
   [['熔融 NaCl','Molten NaCl'],true,'ions',['Na⁺ 和 Cl⁻ 可移動，傳導電流。','Na⁺ and Cl⁻ ions are mobile and carry current.']],
   [['NaCl 水溶液','Aqueous NaCl'],true,'ions',['水中有可自由移動的 Na⁺ 和 Cl⁻。','The water contains mobile Na⁺ and Cl⁻ ions.']],
   [['銅','Copper'],true,'electrons',['金屬中的離域電子可以移動。','Delocalised electrons move through the metal.']],
   [['糖水','Sugar solution'],false,'molecules',['糖分子不帶電，溶解後沒有形成足夠離子。','Sugar molecules are neutral; dissolving does not produce appreciable ions.']],
   [['蒸餾水','Distilled water'],false,'molecules',['只有極少量離子，這個簡化測試的燈泡不會明顯發亮。','There are very few ions, so the bulb does not visibly light in this simple test.']],
   [['石墨','Graphite'],true,'electrons',['石墨雖是非金屬，也有可移動的電子。','Graphite is a non-metal with mobile electrons.']],
  ];count=samples.length;
  renderContent=()=>{const [_name,conducts,kind,reason]=samples[s.index],active=s.tested&&conducts;
   return split(select(t('選擇樣本','Choose a sample'),samples.map(a=>bi(a[0])))+`<p>${t('先預測：燈泡會明顯亮起嗎？','Predict: will the bulb visibly light?')}</p><div class="choice-row">${button(t('會','Yes'),'predict','data-value="yes" aria-pressed="'+(s.prediction==='yes')+'"')}${button(t('不會','No'),'predict','data-value="no" aria-pressed="'+(s.prediction==='no')+'"')}</div><div class="practice-actions">${button(t('接通電路','Test circuit'),'test',s.prediction==null?'disabled':'','primary')}${button(t('下一個例子 →','Next example →'),'next')}</div>`,`<div class="circuit ${active?'circuit-on':''}"><div class="bulb">${active?'✦':'○'}</div><div class="electrodes"><b>−</b><b>+</b></div><div class="particle-box ${active?'mobile':''}">${Array.from({length:12},(_,i)=>`<span style="--i:${i}" class="particle ${kind==='ions'?(i%2?'positive':'negative'):'neutral'}">${kind==='ions'?(i%2?'+':'−'):kind==='electrons'?'e⁻':'●'}</span>`).join('')}</div></div><p>${s.tested?bi(reason):t('先作預測，再看結果。','Make a prediction to reveal the result.')}</p><small>${t('示意電路：只比較導電性，不表示反應產物。','Schematic circuit: compares conductivity, not reaction products.')}</small>`);
  };
  onAction=(action,b)=>{if(action==='predict'){s.prediction=b.dataset.value;s.tested=false;s.feedback='';}if(action==='test'){s.tested=true;const correct=(s.prediction==='yes')===samples[s.index][1];tell(correct?'預測正確！請用「可移動的帶電粒子」解釋。':'再想一想：要同時有「帶電」及「可移動」的粒子。',correct?'Correct prediction. Explain it using mobile charged particles.':'Reconsider: the particles must be both charged and mobile.',correct);}};
 }
 if(type==='names'){
  const tasks=[['Na',1],['NH4',1],['Cu',1],['Cu',2],['Fe',2],['Fe',3],['Al',3],['Cl',-1],['O',-2],['SO4',-2],['NO3',-1],['CO3',-2],['OH',-1],['PO4',-3]].map(([a,q])=>ions.find(i=>i.symbol===a&&i.charge===q));count=tasks.length;
  renderContent=()=>{const target=tasks[s.index],choices=ions.filter(i=>i.symbol===target.symbol||i.charge===target.charge).slice(0,7);if(!choices.includes(target))choices.push(target);
   return `<div class="name-task"><span class="eyebrow">${t('找出正確符號','Find the correct symbol')}</span><h3>${bi(target.name)}</h3><div class="ion-options">${choices.map(i=>button(ionHTML(i),'name',`data-symbol="${i.symbol}" data-charge="${i.charge}"`)).join('')}</div></div><div class="practice-actions">${button(t('提示','Hint'),'hint')}${button(t('下一個例子 →','Next example →'),'next')}</div><details class="reference"><summary>${t('離子參考表：符號、名稱與電荷','Ion reference: symbols, names and charges')}</summary><div class="ion-reference">${ions.map(i=>`<div><b>${ionHTML(i)}</b><span>${bi(i.name)}</span><small>${i.poly?t('多原子離子','Polyatomic ion'):t('簡單離子','Simple ion')}</small></div>`).join('')}</div></details>`;
  };
  onAction=(action,b)=>{const i=tasks[s.index];if(action==='hint')tell(`這個離子的電荷是 ${chargeText(i.charge)}。`,`The charge is ${chargeText(i.charge)}.`);if(action==='name'){const good=b.dataset.symbol===i.symbol&&Number(b.dataset.charge)===i.charge;tell(good?'配對正確！':'未配對成功，留意羅馬數字、下標及電荷。',good?'Correct match.':'Try again: check the Roman numeral, subscript and charge.',good);}};
 }
 if(type==='colours'||type==='lab'){
  /** @type {Array<[string,[string,string],string]>} */
  const colours=[['Cu²⁺',['藍色','Blue'],'#3997d7'],['Fe²⁺',['淡綠色','Pale green'],'#b4d6a2'],['Fe³⁺',['黃／棕色','Yellow / brown'],'#c99628'],['Co²⁺',['粉紅色','Pink'],'#e696b2'],['Ni²⁺',['綠色','Green'],'#65ac68'],['Cr³⁺',['綠色','Green'],'#699566'],['CrO₄²⁻',['黃色','Yellow'],'#e8ce23'],['Cr₂O₇²⁻',['橙色','Orange'],'#e98929'],['Mn²⁺',['極淡粉紅色','Very pale pink'],'#f4dde4'],['MnO₄⁻',['紫色','Purple'],'#9855b7']];
  /** @type {Array<[string,[string,string],string]>} */
  const flames=[['Na',['黃色','Yellow'],'#ffc62e'],['K',['淡紫色','Lilac'],'#c69cec'],['Ca',['磚紅／橙紅色','Brick / orange-red'],'#ec7550'],['Cu',['藍綠色','Blue-green'],'#38c9b2']];
  const list=type==='colours'?colours:flames;count=list.length;
  renderContent=()=>{const [_symbol,name,color]=list[s.index];return split(`<p>${t('觀察顏色，選出可能的','Observe the colour and choose the possible')} ${type==='colours'?t('離子','ion'):t('金屬','metal')}${t('。','.')}</p><div class="ion-options">${list.map((x,i)=>button(x[0],'identify',`data-value="${i}"`)).join('')}</div><div class="practice-actions">${button(t('顯示名稱','Reveal name'),'example')}${button(t('下一個例子 →','Next example →'),'next')}</div>`,type==='colours'?`<div class="test-tube" style="--sample:${color}"><div></div></div><b>${bi(name)}</b><p>${t('水溶液的典型顏色','Typical aqueous solution colour')}</p>`:`<div class="flame-stage"><div class="flame" style="--sample:${color}"></div><div class="burner"></div></div><b>${bi(name)}</b><p>${t('顯示金屬化合物的典型焰色','Typical flame colour of a metal compound')}</p>`)+(type==='lab'?`<section class="migration"><h3>${t('離子會往哪邊走？','Which way will ions move?')}</h3><p>${t('按離子名稱，先預測它被哪一極吸引，再顯示結果。','Choose an ion, predict the electrode that attracts it, then reveal the result.')}</p>${select(t('選擇離子','Choose an ion'),['Cu²⁺','Cr₂O₇²⁻','MnO₄⁻','K⁺'],'migrationIndex')}<p>${bi([['藍色','Blue'],['橙色','Orange'],['紫色','Purple'],['無色：以標籤追蹤它的移動','Colourless: the label lets you track its movement']][s.migrationIndex||0])}</p><div class="choice-row">${button(t('左邊：負極','Left: negative'),'migration-predict','data-value="negative" aria-pressed="'+(s.migrationPrediction==='negative')+'"')}${button(t('右邊：正極','Right: positive'),'migration-predict','data-value="positive" aria-pressed="'+(s.migrationPrediction==='positive')+'"')}${button(t('顯示移動','Show movement'),'migration',!s.migrationPrediction?'disabled':'')}</div><div class="migration-strip ${s.migrated?'migrated':''}"><b>−</b><span style="background:${['#b6dbef','#f3ba74','#d1bfe7','#fff'][s.migrationIndex||0]}" class="migrating-ion ${(s.migrationIndex||0)===0||(s.migrationIndex||0)===3?'to-negative':'to-positive'}">${['Cu²⁺','Cr₂O₇²⁻','MnO₄⁻','K⁺'][s.migrationIndex||0]}</span><b>+</b></div><p role="status">${s.migrationFeedback||t('加濕的濾紙／凝膠提供離子可移動的介質。','Moist filter paper or gel provides a medium for ions to move.')}</p></section>`:`<details class="reference"><summary>${t('比較全部離子顏色','Compare all ion colours')}</summary><div class="colour-reference">${colours.map(([sym,col,c])=>`<div><i style="background:${c}"></i><b>${sym}</b><span>${bi(col)}</span></div>`).join('')}</div><p>${t('Cu²⁺ 的水合離子通常呈藍色；溶液中其他粒子可令觀察到的顏色偏綠。','Hydrated Cu²⁺ is normally blue; other species in solution can shift the observed colour towards green.')}</p></details>`);};
  onAction=(action,b)=>{if(action==='identify'){const good=+b.dataset.value===s.index||(type==='colours'&&[4,5].includes(s.index)&&[4,5].includes(+b.dataset.value));tell(good?(type==='colours'&&[4,5].includes(s.index)?'正確！Ni²⁺ 和 Cr³⁺ 均可呈綠色；顏色不一定能唯一辨認離子。':'配對正確！'):'再看顏色提示，或查看參考。',good?(type==='colours'&&[4,5].includes(s.index)?'Colour match. Ni²⁺ and Cr³⁺ can both be green; colour alone may not identify an ion.':'Correct colour match.'):'Look again at the colour clue, or check the reference.',good);}if(action==='example'){s.revealed=true;tell(`${list[s.index][0]}：${bi(list[s.index][1])}。`,`${list[s.index][0]}: ${bi(list[s.index][1])}.`);}if(action==='migration-predict'){s.migrationPrediction=b.dataset.value;s.migrated=false;s.migrationFeedback='';}if(action==='migration'){const target=[0,3].includes(s.migrationIndex||0)?'negative':'positive';s.migrated=true;s.migrationFeedback=(target===s.migrationPrediction?t('預測正確。','Correct prediction. '):t('再留意電荷。','Check the charge. '))+t(target==='negative'?'正離子被負極吸引。':'負離子被正極吸引。',target==='negative'?'Cations are attracted to the negative electrode.':'Anions are attracted to the positive electrode.');}};
 }

 if(['sharing','bonds','compounds'].includes(type)){
  const set=molecules.filter(m=>type==='sharing'?['H2','HCl'].includes(m.id):type==='bonds'?['Cl2','O2','N2','F2','H2'].includes(m.id):['HCl','H2O','NH3','CH4','CO2','CCl4','PCl3'].includes(m.id));count=set.length;
  renderContent=()=>{const m=set[s.index],nb=m.bonds.length;if(!s.values.length)s.values=Array(nb+m.atoms.length).fill(0);const bonds=s.values.slice(0,nb),lones=s.values.slice(nb);const displayed=moleculeSVG(m,bonds,lones,s.structural);
   return split(select(t('選擇分子','Choose a molecule'),set.map(m=>`${m.id} · ${bi(m.name)}`))+`<p>${t('外層電子總數','Total valence electrons')}: <b>${m.atoms.reduce((n,a)=>n+valence[a.s],0)}</b>. ${t('先加共享電子對，再放剩餘孤電子對。','Add shared pairs, then place the remaining lone pairs.')}</p><h3>${t('共享電子對','Shared pairs')}</h3>`+m.bonds.map(([a,b],i)=>counter(`${m.atoms[a].s}–${m.atoms[b].s} ${m.bonds.length>1?i+1:''}`,s.values[i],i,3)).join('')+`<h3>${t('孤電子對','Lone pairs')}</h3>`+m.atoms.map((a,i)=>counter(`${a.s} ${m.atoms.filter(x=>x.s===a.s).length>1?`· ${t('原子','atom')} ${i+1}`:''}`,s.values[nb+i],nb+i,4)).join('')+actions(),displayed+`<div class="choice-row">${button(t('電子圖','Electron diagram'),'view','data-value="dots" aria-pressed="'+!s.structural+'"')}${button(t('結構式','Structural formula'),'view','data-value="lines" aria-pressed="'+!!s.structural+'"')}</div><div class="model-counts"><span>${t('共享電子','Shared electrons')}: <b>${bonds.reduce((a,b)=>a+b,0)*2}</b></span><span>${t('孤電子','Lone electrons')}: <b>${lones.reduce((a,b)=>a+b,0)*2}</b></span></div>`+legend()+`<p class="diagram-note">${t('平面電子圖，不表示真實分子形狀。結構式的線代表一對共享電子。','A flat electron diagram, not actual molecular shape. Each structural line represents one shared pair.')}</p>`);
  };
  onAction=(action,b)=>{const m=set[s.index],nb=m.bonds.length,target=[...m.bonds.map(b=>b[2]),...m.atoms.map(a=>a.lone)];if(action==='view')s.structural=b.dataset.value==='lines';if(action==='hint')tell('先數總外層電子；H 計 2 粒，其餘本課例子計 8 粒。每條線代表 2 粒共享電子。','Count all valence electrons first. H counts 2; the other atoms in these examples count 8. Each line means 2 shared electrons.');if(action==='example'){s.values=target;s.revealed=true;tell(`示範：${pairTotal(m)} 對成鍵電子；整個分子有 ${loneTotal(m)} 對孤電子。`,`Example: ${pairTotal(m)} bonding pairs and ${loneTotal(m)} lone pairs in the whole molecule.`);}if(action==='check'){
   const total=s.values.reduce((n,x)=>n+x,0)*2,available=m.atoms.reduce((n,a)=>n+valence[a.s],0);
   const around=m.atoms.map((a,i)=>2*(s.values[nb+i]+m.bonds.reduce((n,b,j)=>n+((b[0]===i||b[1]===i)?s.values[j]:0),0)));
   const wrong=around.findIndex((n,i)=>n!==(m.atoms[i].s==='H'?2:8));
   if(s.values.every((n,i)=>n===target[i]))tell('正確！總電子數、共享電子及每個原子的外層都吻合。','Correct: the electron total, shared pairs and each outer shell all match.',true);
   else if(total>available)tell(`你畫了 ${total} 粒電子，但只有 ${available} 粒可用。先移走多出的電子。`,`You drew ${total} electrons but only ${available} are available. Remove the extras.`);
   else if(wrong>=0)tell(`${m.atoms[wrong].s}（圖中第 ${wrong+1} 個原子）現在計到 ${around[wrong]} 粒；應計到 ${m.atoms[wrong].s==='H'?2:8} 粒。`,`Atom ${wrong+1} (${m.atoms[wrong].s}) counts ${around[wrong]} electrons; it should count ${m.atoms[wrong].s==='H'?2:8}.`);
   else tell('外層似乎填滿了，但請再核對總電子數及孤電子位置。','The shells look full, but recheck the total electron count and lone pairs.');
  }};
 }
 if(type==='molecules'){
  const particles=[['He',1],['Ne',1],['Ar',1],['H2',2],['N2',2],['O2',2],['F2',2],['Cl2',2],['O3',3]];count=particles.length;
  renderContent=()=>{const [f,n]=particles[s.index],sym=f.replace(/\d/g,'');return split(`<p class="formula">${formulaHTML(f)}</p><p>${t('一個粒子有多少個原子？','How many atoms are in one particle?')}</p><div class="choice-row">${[1,2,3].map(n=>button(`${n}`,'classify',`data-value="${n}"`)).join('')}</div><p>${t('這些都是元素，只包含一種原子。','These are all elements, containing just one type of atom.')}</p><div class="practice-actions">${button(t('下一個例子 →','Next example →'),'next')}</div>`,`<div class="particle-molecule">${Array.from({length:n},()=>`<span>${sym}</span>`).join('<i></i>')}</div><p>${n===1?t('獨立原子，沒有此原子與另一原子之間的共價鍵。','A separate atom, with no covalent bond to another atom.'):t('數一數相連的小球。這是原子數目模型，沒有顯示鍵級。','Count the joined spheres. This model counts atoms; it does not show bond order.')}</p>`);};
  onAction=(action,b)=>{if(action==='classify'){const n=particles[s.index][1],good=+b.dataset.value===n;tell(good?`正確：${n===1?'單原子粒子':n===2?'雙原子分子':'三原子分子'}。`:'再數一數小球。',good?`Correct: ${n===1?'a monatomic particle':n===2?'a diatomic molecule':'a triatomic molecule'}.`:'Count the spheres again.',good);}};
 }
 if(type==='formulae'){
  count=molecularTasks.length;
  renderContent=()=>{const [_f,a,_na,b,_nb]=molecularTasks[s.index];if(!s.values.length)s.values=[1,1];const bonds={H:1,F:1,Cl:1,I:1,O:2,S:2,N:3,P:3,C:4,Si:4};return split(select(t('選擇成鍵組合','Choose a bonding combination'),molecularTasks.map(x=>`${x[1]} + ${x[3]}`))+`<p>${t('指定本課成鍵數','Bond counts specified for this task')}: <b>${a}: ${bonds[a]}; ${b}: ${bonds[b]}</b></p>`+counter(a,s.values[0],0,6)+counter(b,s.values[1],1,6)+actions(),`<div class="formula large-formula">${a}${s.values[0]===1?'':`<sub>${s.values[0]}</sub>`}${b}${s.values[1]===1?'':`<sub>${s.values[1]}</sub>`}</div><p>${t('每個分子內的原子數','Atoms per molecule')}</p><div class="formula-example"><b>H₂O</b><span>↔</span><b>H–O–H</b></div><p>${t('分子式 ↔ 結構式（此平面式不表示水分子的形狀）','Molecular ↔ structural formula (this flat formula does not show water’s shape)')}</p>`);};
  onAction=action=>{const [f,a,na,b,nb]=molecularTasks[s.index];if(action==='hint')tell('讓兩邊可形成的鍵數相配，再找本課最簡分子組合。','Match the available bond counts, then find the simplest molecule used in this task.');if(action==='example'){s.values=[na,nb];s.revealed=true;tell(`示範：${f}，含 ${na} 個 ${a} 和 ${nb} 個 ${b}。`,`Example: ${f}, containing ${na} ${a} and ${nb} ${b} atoms.`);}if(action==='check'){const good=s.values[0]===na&&s.values[1]===nb;tell(good?`正確！分子式是 ${f}。`:'再核對每種原子的成鍵數及最簡組合。',good?`Correct: the molecular formula is ${f}.`:'Recheck the bond counts and the simplest combination for this task.',good);}};
 }
 if(type==='mass'){
  count=massExamples.length;
  renderContent=()=>{const f=massExamples[s.index],atoms=parseFormula(f);return select(t('選擇化學式','Choose a formula'),massExamples)+split(`<h3 class="formula">${formulaHTML(f)}</h3><p>${t('第一步：數每種原子（括號外的數要乘進去）。','Step 1: count each type of atom, multiplying through brackets.')}</p>`+Object.keys(atoms).map(e=>`<label class="mass-row"><b>${e}</b><span>Aᵣ = ${relativeMass[e]}</span><input type="number" min="0" step="1" inputmode="numeric" aria-label="${t('原子數','Atom count')} ${e}" data-atom="${e}" value="${safe(s.counts?.[e]??'')}"/></label>`).join('')+numberInput(t('第二步：相對質量（沒有單位）','Step 2: relative mass (no unit)'),'total')+actions(),`<div class="mass-visual"><b>Σ (n × Aᵣ)</b>${Object.keys(atoms).map(e=>`<div><span>${e}</span><b>${safe(s.counts?.[e]??'?')} × ${relativeMass[e]}</b></div>`).join('')}<p>${t('分子 → 相對分子質量<br>離子化合物 → 相對式量','Molecule → relative molecular mass<br>Ionic compound → relative formula mass')}</p></div>`);};
  onAction=action=>{const f=massExamples[s.index],atoms=parseFormula(f),answer=massOf(f);if(action==='hint')tell('例如 Ca(NO₃)₂：Ca ×1、N ×2、O ×6；不要只把括號內最後的元素乘 2。','Example Ca(NO₃)₂: Ca ×1, N ×2, O ×6. Multiply every atom inside the bracket by 2.');if(action==='example'){s.counts=atoms;s.total=Number(answer.toFixed(1));s.revealed=true;tell(`示範：${Object.entries(atoms).map(([e,n])=>`${n}×${relativeMass[e]}`).join(' + ')} = ${Number(answer.toFixed(1))}。`,`Example: ${Object.entries(atoms).map(([e,n])=>`${n}×${relativeMass[e]}`).join(' + ')} = ${Number(answer.toFixed(1))}.`);}if(action==='check'){const wrong=Object.keys(atoms).find(e=>String(s.counts?.[e]??'').trim()===''||+s.counts[e]!==atoms[e]);if(wrong)tell(`先修正 ${wrong} 的原子數，特別留意括號及下標。`,`First correct the atom count for ${wrong}; check brackets and subscripts.`);else if(String(s.total??'').trim()===''||Math.abs(+s.total-answer)>.051)tell('原子數正確！再把各項乘積相加，可保留一位小數。','The atom counts are correct. Now add the products; one decimal place is enough.');else tell(`正確！相對質量 = ${Number(answer.toFixed(1))}，沒有單位。`,`Correct: relative mass = ${Number(answer.toFixed(1))}, with no unit.`,true);}};
 }

 function draw(){root.innerHTML=`${renderContent()}${feedback()}`;}
 root.addEventListener('change',event=>{const selectEl=event.target.closest('[data-select]');if(selectEl){const key=selectEl.dataset.select;s[key]=+selectEl.value;if(key==='index')reset();else{s.migrated=false;s.migrationPrediction=null;s.migrationFeedback='';}draw();root.querySelector(`[data-select="${key}"]`)?.focus();}});
 root.addEventListener('input',event=>{const input=event.target;if(input.dataset.input)s[input.dataset.input]=input.value;if(input.dataset.atom){s.counts??={};s.counts[input.dataset.atom]=input.value;}s.feedback='';s.good=false;const message=root.querySelector('.lab-feedback');if(message){message.textContent='';message.className='lab-feedback';}});
 root.addEventListener('click',event=>{const b=event.target.closest('[data-action]');if(!b)return;const action=b.dataset.action;const focusKey=b.dataset.key,focusDelta=b.dataset.delta;
  if(action==='next'){s.index=(s.index+1)%count;reset();}
  else if(action==='count'){const i=+b.dataset.key;s.values[i]=Math.max(0,Math.min(+(b.dataset.max||99),s.values[i]+(+b.dataset.delta)));s.feedback='';s.good=false;}
  else onAction?.(action,b);
  s.mode=['check','identify','name','classify','test'].includes(action)?(s.good?'correct':'error'):'info';
  draw();const focus=root.querySelector(action==='count'?`[data-key="${focusKey}"][data-delta="${focusDelta}"]:not(:disabled)`:`[data-action="${action}"]:not(:disabled)`)||(action==='count'?root.querySelector(`[data-key="${focusKey}"]:not(:disabled)`):null);focus?.focus({preventScroll:true});
 });
 draw();
}
