const notes = {
  properties: ['用性質解釋用途','Link a property to a use','為何銅適合製作電線？','Why is copper suitable for electrical wires?','銅導電良好，讓電流通過；而且有延性，可拉成細線。','Copper conducts electricity well and is ductile, so it can be drawn into wires.','展性 = 薄片；延性 = 細線。兩個字不要混淆。','Malleable → sheets. Ductile → wires. Keep the two terms separate.'],
  history: ['容易提取，才較早用得上','Extraction difficulty helps explain the order','鋁在地殼中很豐富，為何較遲才廣泛使用？','Aluminium is abundant. Why did its widespread use come later?','鋁很活潑，其化合物難以還原。發展電解技術後，才可大量提取。','Aluminium is very reactive and its compounds are difficult to reduce. Large-scale extraction became possible with electrolysis.','含量高，不代表容易提取。','Abundant does not mean easy to extract.'],
  sources: ['礦物、礦石、金屬要分清','Distinguish a mineral, an ore and a metal','所有含金屬的岩石都算礦石嗎？','Is every metal-containing rock an ore?','不是。金屬含量和提取成本必須令開採有經濟價值。','No. The metal content and extraction cost must make extraction economically worthwhile.','鋁最多是指「金屬」；地殼中最多的元素是氧。','Aluminium is the most abundant metal; oxygen is the most abundant element in the crust.'],
  simple: ['新物質有沒有形成？','Did a new substance form?','為何淘金是物理方法，而加熱銀氧化物是化學方法？','Why is panning physical, but heating silver oxide chemical?','淘金只分離已有的金；銀氧化物受熱後形成銀和氧氣兩種新物質。','Panning separates existing gold. Heating silver oxide forms two new substances: silver and oxygen.','不是所有金屬氧化物都可以只靠加熱提取。','Heating alone does not work for every metal oxide.'],
  carbon: ['先寫物質名稱，再檢查氧的去向','Write the names, then track the oxygen','氧化銅與碳加熱後，觀察到甚麼？如何解釋？','What is observed when copper oxide is heated with carbon? Explain.','黑色混合物中出現紅棕色銅。碳拿走氧化銅中的氧，氧化銅被還原。','Reddish-brown copper appears in the black mixture. Carbon removes oxygen from copper oxide, reducing it.','觀察寫顏色變化；解釋才寫「失去氧／還原」。','Observation: colour change. Explanation: oxygen removed / reduction.'],
  electrolysis: ['鋁在負極形成','Aluminium forms at the cathode','為何含鋁的電解質必須是熔融狀態？','Why must the aluminium-containing electrolyte be molten?','熔融狀態中，帶電的離子能移動並傳導電流。','In the molten state, charged ions can move and carry the electric current.','移動的是離子；不要說氧化鋁「融化成鋁」。','Ions move. Melting aluminium oxide does not turn it into aluminium.'],
  rust: ['水和氧氣，要同時有','Water and oxygen must both be present','為何煮沸的水上面還要加油層？','Why add an oil layer above boiled water?','煮沸已除去溶解氧；油層可防止空氣中的氧氣再次溶入水中。','Boiling removes dissolved oxygen. Oil prevents oxygen from the air dissolving back into the water.','油層的作用是隔絕氧氣，不是把水吸走。','Oil excludes oxygen; it does not absorb the water.'],
  protect: ['先講方法，再講保護原理','Name the method, then explain how it works','為何鐵門的油漆刮破後，要補漆？','Why should scratched paint on an iron gate be repaired?','刮痕令水和氧氣接觸鐵，鐵便可能生銹。補漆可恢復屏障。','Scratches expose iron to water and oxygen, allowing rust. Repainting restores the barrier.','不銹鋼是合金，不是鐵表面的一層漆。','Stainless steel is an alloy, not a painted coating.'],
};
export function renderExamNote(id,en) {
  const n=notes[id], t=(zh,english)=>en?english:zh;
  return `<section class="exam-note"><div class="exam-note-heading"><span>${t('答題練習','EXAM PRACTICE')}</span><h2>${t(n[0],n[1])}</h2></div><p class="exam-question">${t(n[2],n[3])}</p><details><summary>${t('看看怎樣答','See a model answer')}</summary><p>${t(n[4],n[5])}</p></details><div class="exam-trap"><b>${t('小心混淆','WATCH OUT')}</b><p>${t(n[6],n[7])}</p></div></section>`;
}
