'use client';
import {ArrowRight,Blocks,Pickaxe,Lightbulb} from 'lucide-react';
import {useLanguage} from './i18n';
import Model from './model';
export default function BuildingBlocks(){
 const {language}=useLanguage(),en=language==='en';
 const examples=[{kind:'Cu',name:en?'Pure copper':'純銅',parts:en?'Copper atoms only':'只有銅原子',symbols:'Cu'},{kind:'H2O',name:en?'Water':'水',parts:en?'Hydrogen and oxygen atoms':'氫原子和氧原子',symbols:'H + O'},{kind:'CO2',name:en?'Carbon dioxide':'二氧化碳',parts:en?'Carbon and oxygen atoms':'碳原子和氧原子',symbols:'C + O'}];
 return <section className="building-blocks"><div className="section-label"><h2>{en?'Everyday objects are made of atoms.':'身邊的物體，都由原子組成。'}</h2><span>{en?'Object → atoms → symbols':'物體 → 原子 → 元素符號'}</span></div><p className="blocks-intro">{en?'Different materials contain different types of atoms.':'不同物質，可以含有不同種類的原子。'}</p><div className="three-grid atom-examples">{examples.map(e=><article className="card" key={e.kind}><h3>{e.name}</h3><Model kind={e.kind} compact label={`${e.name}: ${e.parts}`}/><div className="example-composition"><span>{e.parts}</span><b>{e.symbols}</b></div></article>)}</div><div className="note"><Lightbulb size={20}/><p>{en?'Water and carbon dioxide both contain oxygen atoms.':'水和二氧化碳，都含有氧原子。'}</p></div><div className="section-label"><h2>{en?'Each type of atom has its own symbol.':'每種原子，都有自己的元素符號。'}</h2><span>Chemical symbol</span></div><p className="blocks-intro">{en?'Each element has a chemical symbol.':'每種元素都有自己的元素符號。'}</p><div className="atom-symbol-map">{[['氫原子','Hydrogen atom','H'],['氧原子','Oxygen atom','O'],['碳原子','Carbon atom','C'],['銅原子','Copper atom','Cu']].map(([zh,english,symbol])=><div key={symbol}><span>{en?english:zh}</span><ArrowRight size={16}/><strong>{symbol}</strong></div>)}</div><div className="section-label"><h2>{en?'Think of LEGO bricks and Minecraft blocks.':'想像 LEGO 積木和 Minecraft 方塊。'}</h2><span>{en?'A building-block analogy':'用熟悉的例子來想像'}</span></div><div className="two-grid analogy-grid"><article className="card"><div className="analogy-title"><Blocks size={26}/><h3>LEGO</h3></div><div className="analogy-flow"><span>{en?'Different bricks':'不同的積木'}<small>Bricks</small></span><ArrowRight size={20}/><span>{en?'A LEGO model':'一件 LEGO 作品'}</span></div><p>{en?'Same bricks, different arrangements, different models.':'同一批積木，換個砌法，就有不同作品。'}</p></article><article className="card"><div className="analogy-title"><Pickaxe size={26}/><h3>Minecraft</h3></div><div className="analogy-flow"><span>{en?'Different blocks':'不同的方塊'}<small>Blocks</small></span><ArrowRight size={20}/><span>{en?'A Minecraft build':'一座 Minecraft 建築'}</span></div><p>{en?'Different blocks can form different buildings.':'不同方塊，可以砌成不同建築。'}</p></article></div><div className="analogy-takeaway"><span>{en?'Bricks / blocks':'積木／方塊'}</span><span>↔</span><b>{en?'Atoms':'原子'}</b><span className="mapping-divider"/><span>{en?'The finished model':'砌好的作品'}</span><span>↔</span><b>{en?'An everyday object':'身邊的物體'}</b></div></section>;
}
