'use client';
import {useTranslateTree,asset} from './i18n';
import { useEffect, useMemo, useRef, useState } from 'react';
import { RotateCcw, ZoomIn, ZoomOut, MoveHorizontal } from 'lucide-react';
import {makeScene,COLORS,names} from './molecules';
export {makeScene,molecule,COLORS} from './molecules';
export default function Model({kind,compact=false,label,angle:sharedAngle,onAngleChange}:{kind:string;compact?:boolean;label?:string;angle?:number;onAngleChange?:(n:number)=>void}){
 const tr=useTranslateTree();

 const ref=useRef<HTMLCanvasElement>(null),drag=useRef<{x:number;y:number;startX:number;startY:number}|null>(null),hit=useRef<{x:number;y:number;r:number;e:string}[]>([]);
 const [rotation,setRotation]=useState({x:-.15,y:.15}),[zoom,setZoom]=useState(1),[selected,setSelected]=useState('');const ry=sharedAngle??rotation.y;
 const scene=useMemo(()=>makeScene(kind),[kind]);
 useEffect(()=>{setSelected('');setZoom(1);},[kind]);
 useEffect(()=>{const canvas=ref.current;if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;
 function draw(){if(!canvas||!ctx)return;const rect=canvas.getBoundingClientRect(),w=rect.width,h=rect.height;if(!w||!h)return;const dpr=Math.min(window.devicePixelRatio||1,2);if(canvas.width!==Math.round(w*dpr))canvas.width=Math.round(w*dpr);if(canvas.height!==Math.round(h*dpr))canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const multi=kind.includes(':'),scale=Math.min(w/(multi?5.6:5.2),h/(multi?4.3:3.5))*zoom;
 const ps=scene.balls.map(a=>{const x=a.x*Math.cos(ry)+a.z*Math.sin(ry),z=-a.x*Math.sin(ry)+a.z*Math.cos(ry),y=a.y*Math.cos(rotation.x)-z*Math.sin(rotation.x),zz=a.y*Math.sin(rotation.x)+z*Math.cos(rotation.x),perspective=7/(7-zz);return {...a,px:w/2+x*scale*perspective,py:h/2-y*scale*perspective,pz:zz,pr:(a.r??(a.e==='H'?.39:.57))*scale*perspective};});ctx.lineCap='round';scene.bonds.forEach(([a,b])=>{ctx.beginPath();ctx.moveTo(ps[a].px,ps[a].py);ctx.lineTo(ps[b].px,ps[b].py);ctx.strokeStyle='#92a9bb';ctx.lineWidth=(multi?5:15)*zoom;ctx.stroke();});hit.current=[];
 [...ps].sort((a,b)=>a.pz-b.pz).forEach(a=>{const g=ctx.createRadialGradient(a.px-a.pr*.33,a.py-a.pr*.4,a.pr*.02,a.px,a.py,a.pr);g.addColorStop(0,'#fff');g.addColorStop(.25,COLORS[a.e]||'#9da7bd');g.addColorStop(1,a.e==='H'?'#8c9dad':'#263a55');ctx.beginPath();ctx.arc(a.px,a.py,a.pr,0,Math.PI*2);ctx.shadowColor='#08183140';ctx.shadowBlur=multi?5:18;ctx.shadowOffsetY=4;ctx.fillStyle=g;ctx.fill();ctx.shadowBlur=0;ctx.shadowOffsetY=0;ctx.fillStyle=['H','S','fat'].includes(a.e)?'#243448':'#fff';const symbol=['mud','fat','food','other'].includes(a.e)?'':a.e;ctx.font=`700 ${Math.max(10,Math.min(30,a.pr*.8))}px Arial`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(symbol,a.px,a.py+1);hit.current.push({x:a.px,y:a.py,r:a.pr,e:a.e});});}
 const observer=new ResizeObserver(draw);observer.observe(canvas);draw();return()=>observer.disconnect();},[kind,scene,rotation.x,ry,zoom]);
 const rotate=(n:number)=>{if(onAngleChange)onAngleChange(ry+n);else setRotation(r=>({...r,y:r.y+n}));};
 return tr(<div className={`molecule-view ${compact?'compact':''}`}><canvas ref={ref} tabIndex={0} role="img" aria-label={label||`${kind} 三維模型，可拖曳或用方向鍵旋轉`} onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();rotate(e.key==='ArrowRight'?.15:-.15);}if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();setRotation(r=>({...r,x:r.x+(e.key==='ArrowUp'?.15:-.15)}));}}} onPointerDown={e=>{drag.current={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!drag.current)return;const dx=(e.clientX-drag.current.x)*.009,dy=(e.clientY-drag.current.y)*.009;rotate(dx);setRotation(r=>({...r,x:r.x+dy}));drag.current={...drag.current,x:e.clientX,y:e.clientY};}} onPointerUp={e=>{const didDrag=drag.current&&Math.hypot(e.clientX-drag.current.startX,e.clientY-drag.current.startY)>5;drag.current=null;if(didDrag)return;const r=e.currentTarget.getBoundingClientRect(),a=[...hit.current].reverse().find(a=>Math.hypot(a.x-(e.clientX-r.left),a.y-(e.clientY-r.top))<a.r);if(a)setSelected(`${a.e.length<3?a.e+' · ':''}${names[a.e]||a.e}`);}} onPointerCancel={()=>drag.current=null}>模型：{label||kind}。H 代表氫，O 代表氧，N 代表氮。</canvas><div className="model-tools"><span className="drag-hint"><MoveHorizontal size={14}/> 拖曳旋轉</span><div><button aria-label="縮小模型" onClick={()=>setZoom(v=>Math.max(.65,v-.15))}><ZoomOut size={17}/></button><button aria-label="放大模型" onClick={()=>setZoom(v=>Math.min(1.6,v+.15))}><ZoomIn size={17}/></button><button aria-label="重設模型" onClick={()=>{setRotation({x:-.15,y:.15});onAngleChange?.(.15);setZoom(1);setSelected('');}}><RotateCcw size={16}/></button></div></div>{selected&&<output className="atom-selected" aria-live="polite">{selected}</output>}</div>);
}

